ALTER TABLE game_owner
    ADD session BIGINT;

ALTER TABLE game_owner
    ADD CONSTRAINT FK_GAMEOWNER_ON_SESSION FOREIGN KEY (session) REFERENCES session (id);

ALTER TABLE GAME_OWNER
    DROP CONSTRAINT FK_GAMEOWNER_ON_OWNER;

ALTER TABLE GAME_OWNER
    DROP COLUMN OWNER_ID;