ALTER TABLE game
    ADD owner_id BIGINT;

ALTER TABLE game_owner
    ADD session_id BIGINT;

ALTER TABLE game_owner
    ADD CONSTRAINT FK_GAMEOWNER_ON_SESSION FOREIGN KEY (session_id) REFERENCES session (id);

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_OWNER FOREIGN KEY (owner_id) REFERENCES game_owner (id);

ALTER TABLE GAME_OWNER
    DROP CONSTRAINT FK_GAMEOWNER_ON_OWNER;

ALTER TABLE GAME_OWNER
    DROP COLUMN OWNER_ID;