ALTER TABLE session
    ADD game BIGINT;

ALTER TABLE game
    ADD session BIGINT;

ALTER TABLE game
    ADD CONSTRAINT FK_GAME_ON_SESSION FOREIGN KEY (session) REFERENCES session (id);

ALTER TABLE session
    ADD CONSTRAINT FK_SESSION_ON_GAME FOREIGN KEY (game) REFERENCES game (id);

ALTER TABLE SESSION
    DROP CONSTRAINT FK_SESSION_ON_OWNING_GAME;

ALTER TABLE SESSION
    DROP COLUMN OWNING_GAME_ID;